# apiVersion: v1
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: "porte-e"
  annotations:
    openshift.io/description: "Porte-e - Expérimentation du portefeuille en tant qu'employé"
    openshift.io/display-name: "Experimentation Port-e - RFID"
    openshift.io/sa.scc.uid-range: "1000/10000"
    openshift.io/sa.scc.supplemental-groups: "1000/10000"
    openshift.io/sa.scc.mcs: "s0:c10,c0"
