version : "3.1"
services: 
  db:
    container_name: ${APP}-postgresdb-${SUFFIX}
    image: postgres:15.1
    ports:
      - 5432:5432
    networks:
      - ${NETWORK}
    volumes:
      - ./data/postgres-data:/data/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  omnidb:
    container_name: ${APP}-omnidb-${SUFFIX}
    image: omnidbteam/omnidb
    ports: [ "8000:8000"]
    networks: 
      - ${NETWORK} 

  node-red:
    image: nodered/node-red:latest
    container_name: ${APP}-node-red-${SUFFIX}
    environment:
      - TZ=${TIMEZONE}
    networks:
      - ${NETWORK} 
    ports:
      - 1880:1880
    volumes:
      - ./.nodered/data:/data

  mosquitto:
    image: eclipse-mosquitto
    container_name: ${APP}-mosquitto-${SUFFIX}
    networks:
      - ${NETWORK} 
    ports:
      - 1833:1833
      - 9001:9001
    volumes:
      - ./.mosquitto:/mosquitto
      - ./.mosquitto/data:/mosquitto/data
      - ./.mosquitto/log:/mosquitto/log


networks:
  garoa-net:
    driver: bridge